const WAF_SIGNATURES = [
  {
    name: "Cloudflare",
    signals: [
      { type: "header", key: "cf-ray" },
      { type: "header", key: "cf-cache-status" },
      { type: "header", key: "cf-connecting-ip" },
      { type: "cookie", key: "__cf_bm" },
      { type: "cookie", key: "cf_clearance" },
    ],
  },
  {
    name: "AWS WAF / CloudFront",
    signals: [
      { type: "header", key: "x-amz-cf-id" },
      { type: "header", key: "x-amz-cf-pop" },
      { type: "header", key: "x-amzn-requestid" },
      { type: "header", key: "x-amz-waf" },
    ],
  },
  {
    name: "Akamai",
    signals: [
      { type: "header", key: "x-akamai-transformed" },
      { type: "header", key: "x-akamai-request-id" },
      { type: "header", key: "akamai-origin-hop" },
      { type: "cookie", key: "ak_bmsc" },
    ],
  },
  {
    name: "Sucuri / GoDaddy WAF",
    signals: [
      { type: "header", key: "x-sucuri-id" },
      { type: "header", key: "x-sucuri-cache" },
      { type: "header", key: "x-sucuri-block" },
    ],
  },
  {
    name: "Vercel",
    signals: [
      { type: "header", key: "x-vercel-id" },
      { type: "header", key: "x-vercel-cache" },
      { type: "header", key: "x-vercel-ip-country" },
    ],
  },
  {
    name: "Netlify",
    signals: [
      { type: "header", key: "x-nf-request-id" },
      { type: "header", key: "x-nf-cache-owner" },
    ],
  },
  {
    name: "Fastly",
    signals: [
      { type: "header", key: "x-served-by" },
      { type: "header", key: "x-cache" },
      { type: "header", key: "x-cache-hits" },
      { type: "header", key: "x-timer" },
      { type: "header", key: "fastly-ff" },
    ],
  },
  {
    name: "Imperva / Incapsula",
    signals: [
      { type: "header", key: "x-iinfo" },
      { type: "header", key: "x-cdn" },
      { type: "cookie", key: "incap_ses_" },
      { type: "cookie", key: "visid_incap_" },
    ],
  },
  {
    name: "ModSecurity (generic WAF)",
    signals: [
      { type: "header", key: "x-modsecurity" },
      { type: "status", value: 403, bodyPattern: /ModSecurity|mod_security|This request was blocked/i },
      { type: "status", value: 406, bodyPattern: /Not Acceptable|mod_security/i },
    ],
  },
  {
    name: "Wordfence (WordPress WAF)",
    signals: [
      { type: "header", key: "x-powered-by", value: /wordfence/i },
      { type: "body", pattern: /Generated by Wordfence|wordfence_lh|wordfence_syncAttackData/i },
    ],
  },
];

export function fingerprintWaf(headers, cookies, body) {
  const detected = [];

  for (const waf of WAF_SIGNATURES) {
    let matches = 0;
    for (const sig of waf.signals) {
      if (sig.type === "header") {
        const val = headers?.[sig.key];
        if (val !== undefined && val !== null) {
          if (sig.value) {
            if (typeof sig.value === "string" && String(val).includes(sig.value)) matches++;
            else if (sig.value instanceof RegExp && sig.value.test(String(val))) matches++;
          } else {
            matches++;
          }
        }
      }
      if (sig.type === "cookie") {
        const cookieKeys = (cookies || []).map(c => c.split("=")[0]);
        if (cookieKeys.some(k => k === sig.key || k.toLowerCase().startsWith(sig.key.toLowerCase()))) {
          matches++;
        }
      }
      if (sig.type === "status" && sig.value === sig.value) {
        // body-based checks
        if (body && sig.bodyPattern && sig.bodyPattern.test(body)) matches++;
      }
      if (sig.type === "body" && body && sig.pattern) {
        if (sig.pattern.test(body)) matches++;
      }
    }

    if (matches > 0) {
      const confidence = matches >= 3 ? "high" : matches >= 2 ? "medium" : "low";
      detected.push({ name: waf.name, confidence, signalCount: matches, totalSignals: waf.signals.length });
    }
  }

  return detected;
}

export function generateWafFix(detected) {
  if (!detected.length) return null;
  const recommendations = [];
  const waf = detected[0];

  switch (waf.name) {
    case "Cloudflare":
      recommendations.push("Ensure 'Bot Fight Mode' or 'WAF Managed Rules' are enabled in Cloudflare dashboard");
      recommendations.push("Set Security Level to at least 'Medium' under Security > Settings");
      recommendations.push("Enable 'Browser Integrity Check' to block automated attacks");
      break;
    case "AWS WAF / CloudFront":
      recommendations.push("Verify AWS WAF Web ACL rules are attached to this CloudFront distribution");
      recommendations.push("Enable AWS Managed Rules baseline rule group (AWS-AWSManagedRulesCommonRuleSet)");
      break;
    case "Vercel":
      recommendations.push("Enable Vercel WAF from the project Settings > Security tab");
      recommendations.push("Add custom firewall rules for rate limiting on /api routes");
      break;
    default:
      recommendations.push(`Verify ${waf.name} WAF rules are actively blocking, not just logging`);
      recommendations.push("Test WAF with common attack payloads to ensure rules trigger correctly");
  }

  return { waf: waf.name, confidence: waf.confidence, recommendations };
}
