// VibeCode — heuristic detector for how "vibe-coded" (low-effort AI-generated) a site looks.
// Signals are evidence-based, each with a weight; higher score = more template-y / less trustworthy-looking.
// Score is normalized via tanh so it saturates around 0-100.

const SRC_RE =
  /(vite\.svg|react\.svg|create-react-app|create-next-app|vitejs|cdn\.tailwindcss\.com|via\.placeholder\.com|placehold\.co|dummyimage\.com|next\/static|_next\/static|logo192\.svg|logo512\.png|manifest\.json|\.cursorrules|\.cursor\/|copilot|chatgpt|claude\.ai|generated by|generated with|<!--generated)/gi;

// Free third-party proxies / "no backend needed" services — the #1 vibe-coded tell
const PROXY_RE =
  /(workers\.dev|onrender\.com|replit\.(?:app|co|dev)|glitch\.me|herokuapp\.com|cyclic\.app|fly\.dev|deno\.dev|koyeb\.app|netlify\.app|vercel\.app|serverless\.sclp\.|lrclib\.net|ytmusicapi|i\.ytimg\.com|youtube\.com\/embed|music\.youtube|youtube-nocookie|spotify\.com\/embed|soundcloud\.com\/embed|api\.genius\.com|rapidapi\.com)/gi;

const TITLE_RE = /(^document$|^react app$|^vite \+ react$|^next\.js$|^my (new )?site$|^new site$|^untitled$|^sample$|^home$|^index$|^demo$|^test$)/i;

const FILLER_RE = /(lorem ipsum|your content goes here|click to (edit|change)|replace this (text|placeholder)|coming soon|this is a placeholder|sample text|example\.com|placeholder image|dummy (image|text)|get started for free|discover your sound|find your sound|welcome to my (portfolio|website))/gi;

const PLACEHOLDER_LINK_RE = /href=["'](?:#|javascript:void\(0\)|javascript:;)["']/gi;

const DEBUG_RE = /(console\.log\(|debugger;|TODO:|FIXME:|XXX:|HACK:)/gi;

const POWERED_RE = /(powered by|made with [\u2764\u2661]|built with|template by|free template|bootstrap template|html5up|startbootstrap|templateza)/gi;

const MOCK_RE =
  /(mockup data|mock data|dummy data|sample data|fake data|placeholder data|hardcoded|seed data|demo data|hard-coded|sample songs|preview songs)/gi;

const YTID_RE = /(?:youtube\.com\/watch\?v=|youtu\.be\/|i\.ytimg\.com\/vi\/)([A-Za-z0-9_-]{11})/g;

const DEAD_FORM_RE = /action=["']?["']?[^>]*>\s*<(?:input|button)[^>]*type=["'](?:text|email)["'][^>]*>\s*<(?:input|button)[^>]*type=["']submit["']/gi;

export function detectVibeCode(meta = {}) {
  const src = meta.vibeSources || {};
  const html = (src.html || "") + " " + (src.js || "");
  const pages = meta.pagesCrawled || 0;
  const signals = [];
  const push = (name, weight, detail, evidence) => signals.push({ name, weight, detail, evidence: (evidence || detail).slice(0, 140) });

  // Boilerplate framework scaffolds
  if (/vite\.svg|@vitejs|vite\/(client)/i.test(html)) push("Vite scaffold leftovers", 12, "Ships the stock Vite logo/boilerplate — the tell-tale sign of `npm create vite`", "vite.svg / @vitejs markers");
  if (/react\.svg|create-react-app|logo192|logo512|react-app\.(css|js)/i.test(html)) push("Create-React-App leftovers", 12, "Default CRA logos and boilerplate in source", "react.svg / logo192.svg");
  if (/_next\/static|create-next-app/i.test(html)) push("Next.js default template", 10, "Stock create-next-app scaffolding", "_next/static boilerplate");
  if (/cdn\.tailwindcss\.com/i.test(html)) push("Tailwind Play CDN", 10, "Uses the in-browser Play CDN instead of a real build step", "cdn.tailwindcss.com");

  // Free third-party proxies / services-as-backend
  const proxies = new Set(html.match(PROXY_RE) || []);
  if (proxies.size) {
    const freeHosts = [...proxies].filter((p) => /workers\.dev|onrender\.com|replit|glitch\.me|herokuapp|cyclic\.app|fly\.dev|koyeb\.app|vercel\.app|netlify\.app/.test(p));
    push(
      "Free third-party proxies as backend",
      14,
      `${proxies.size} free/unofficial service(s) used as the backend (${[...proxies].slice(0, 4).join(", ")}) — no real backend, data likely mock.`,
      [...proxies].slice(0, 3).join(", ")
    );
    if (freeHosts.length) push("Unofficial proxy services", 10, "Depends on random free proxies (e.g. *.workers.dev) that can vanish any day", freeHosts.slice(0, 3).join(", "));
  }

  // Hardcoded seed / mock data (repeated embedded IDs)
  YTID_RE.lastIndex = 0;
  const ytIds = new Set(html.match(YTID_RE) || []);
  if (ytIds.size >= 3) push("Hardcoded seed/mock content", 12, `${ytIds.size} embedded media IDs hardcoded in source — sample/demo data, not real content`, [...ytIds].slice(0, 3).join(", "));

  // SPA catch-all: many routes, near-identical shells
  const pagesTotal = pages;
  const unique = meta.uniquePages || 0;
  if (pagesTotal > 4 && unique <= 2) push("All routes serve one SPA shell", 11, `${pagesTotal} URLs all return the same index.html — typical of a scaffolded client-side demo`, `${unique} unique / ${pagesTotal} pages`);

  // Filler / placeholder content
  const filler = (html.match(FILLER_RE) || []).slice(0, 4);
  if (filler.length) push("Placeholder copy left in", 12, "Lorem ipsum / 'click to edit' / marketing-slogan filler left in the shipped site", filler.join(", "));

  // Mock-data markers
  const mock = (html.match(MOCK_RE) || []).slice(0, 3);
  if (mock.length) push("Mock / sample data markers", 9, "Source explicitly references mock or sample data", mock.join(", "));

  // Default titles
  const titles = (meta.titles || []).filter(Boolean);
  const defaultTitle = titles.some((t) => TITLE_RE.test(t));
  if (defaultTitle) push("Default page titles", 8, "Pages still have generator-default titles ('React App', 'Vite + React'…)", titles.join(", "));

  // Dead placeholder links
  const deadLinks = (html.match(PLACEHOLDER_LINK_RE) || []).length;
  if (deadLinks > 1) push("Dead placeholder links", 8, `${deadLinks} links point to '#' or javascript:void(0)`, `${deadLinks} occurrences`);

  // Debug leftovers
  const debug = (html.match(DEBUG_RE) || []).length;
  if (debug > 2) push("Debug code left in", 9, `${debug} console.log / TODO / debugger leftovers in shipped source`, `${debug} occurrences`);

  // Template / powered-by footers
  const powered = (html.match(POWERED_RE) || []).length;
  if (powered) push("Template / 'powered by' markers", 7, `${powered} template or 'powered by' markers — stock theme instead of bespoke build`, `${powered} occurrences`);

  // Missing trust markers
  if (!meta.robots) push("No robots.txt", 5, "No robots.txt found — small signal it was never finished", "robots.txt missing");

  // Placeholder image services
  if (/via\.placeholder\.com|placehold\.co|dummyimage\.com/i.test(html)) push("Placeholder image service", 9, "Ships placeholder image URLs", "via.placeholder.com");

  // AI assistant fingerprints
  const aiTools = html.match(/(\.cursorrules|\.cursor\/|copilot|chatgpt|claude\.ai|generated by|generated with|<!--generated)/gi) || [];
  if (aiTools.length) push("AI-generation fingerprints", 8, "Source mentions AI tools / 'generated with' comments", aiTools.slice(0, 3).join(", "));

  // Boilerplate forms
  const deadForm = html.match(DEAD_FORM_RE);
  if (deadForm) push("Template signup form", 6, "Stock newsletter/subscribe form with empty action", deadForm[0].slice(0, 90));

  // Thin content
  if (pagesTotal <= 2) push("Thin content", 6, `Only ${pagesTotal} page(s) — a prototype, not a product`, `${pagesTotal} pages crawled`);

  // Stock favicon
  if (/favicon\.ico/i.test(html) && !/rel=["']icon["'][^>]*\.svg/.test(html)) push("Stock favicon", 4, "No custom favicon — browsers fall back to /favicon.ico", "/favicon.ico");

  const actual = signals.reduce((a, s) => a + s.weight, 0);
  const score = Math.round(100 * Math.tanh(actual / 60));

  let label = "Custom build";
  if (score >= 70) label = "Full AI prototype";
  else if (score >= 45) label = "Template-ish build";
  else if (score >= 20) label = "Semi-custom build";

  return {
    score,
    label,
    signalCount: signals.length,
    signals: signals.slice(0, 25),
    summary: signals.length
      ? `Detected ${signals.length} vibe-coding signals. Highest-signal: ${signals[0]?.name}.`
      : "No obvious vibe-coding signals detected.",
  };
}
