// VibeCode — heuristic detector for how "vibe-coded" (low-effort AI-generated) a site looks.
// Signals are evidence-based, each with a weight; higher score = more template-y / less trustworthy-looking.

const SRC_RE = /(vite\.svg|react\.svg|create-react-app|create-next-app|vitejs|cdn\.tailwindcss\.com|via\.placeholder\.com|placehold\.co|dummyimage\.com|next\/static|_next\/static|logo192\.svg|logo512\.png|manifest\.json|\.cursorrules|cursor\/|copilot|chatgpt|claude\.ai|generated by|generated with|<!--generated)/gi;

const TITLE_RE = /(^document$|^react app$|^vite \+ react$|^next\.js$|^my (new )?site$|^new site$|^untitled$|^sample$|^home$|^index$)/i;

const FILLER_RE = /(lorem ipsum|your content goes here|click to (edit|change)|replace this (text|placeholder)|coming soon placeholder|this is a placeholder|sample text|example\.com|placeholder image|dummy (image|text)|get started for free)/gi;

const PLACEHOLDER_LINK_RE = /href=["'](?:#|javascript:void\(0\)|javascript:;)["']/gi;

const DEBUG_RE = /(console\.log\(|debugger;|TODO:|FIXME:|XXX:|HACK:)/gi;

const DEAD_FORM_RE = /action=["'"]?["']?[^>]*>\s*<(?:input|button)[^>]*type=["'](?:text|email)["'][^>]*>\s*<(?:input|button)[^>]*type=["']submit["']/gi;

const BOILERPLATE_OG_RE = /og:image.*?\/assets\/(?:og|cover|banner)/i;

export function detectVibeCode(meta = {}) {
  const src = meta.vibeSources || {};
  const html = (src.html || "") + " " + (src.js || "");
  const pages = meta.pagesCrawled || 0;
  const signals = [];
  const push = (name, weight, detail, evidence) => signals.push({ name, weight, detail, evidence: (evidence || detail).slice(0, 140) });

  // Boilerplate framework scaffolds
  if (/vite\.svg|@vitejs|vite\/(client)/i.test(html)) push("Vite scaffold leftovers", 12, "Ships the stock Vite logo/boilerplate — the tell-tale sign of `npm create vite`", "vite.svg / @vitejs markers");
  if (/react\.svg|create-react-app|logo192|logo512|react-app\.(css|js)/i.test(html)) push("Create-React-App leftovers", 12, "Default CRA logos and boilerplate in source", "react.svg / logo192.svg");
  if (/_next\/static|create-next-app/i.test(html)) push("Next.js default template", 10, "Stock create-next-app scaffolding", "_next/static boilerplate");
  if (/cdn\.tailwindcss\.com/i.test(html)) push("Tailwind Play CDN", 10, "Uses the in-browser Play CDN instead of a real build step", "cdn.tailwindcss.com");

  // Filler / placeholder content
  const filler = (html.match(FILLER_RE) || []).slice(0, 4);
  if (filler.length) push("Placeholder copy left in", 12, "Lorem ipsum / 'click to edit' filler text left in the shipped site", filler.join(", "));

  // Default titles
  const titles = (meta.titles || []).filter(Boolean);
  const defaultTitle = titles.some((t) => TITLE_RE.test(t));
  if (defaultTitle) push("Default page titles", 8, "Pages still have generator-default titles ('React App', 'Vite + React'…)", titles.join(", "));

  // Dead placeholder links
  const deadLinks = (html.match(PLACEHOLDER_LINK_RE) || []).length;
  if (deadLinks > 1) push("Dead placeholder links", 8, `${deadLinks} links point to '#' or javascript:void(0)`, `${deadLinks} occurrences`);

  // Debug leftovers
  const debug = (html.match(DEBUG_RE) || []).length;
  if (debug > 2) push("Debug code left in", 9, `${debug} console.log / TODO / debugger leftovers in shipped source`, `${debug} occurrences`);

  // Missing trust markers
  if (!meta.robots) push("No robots.txt", 5, "No robots.txt found — small signals it was never finished", "robots.txt missing");
  if (!meta.subdomains) push("Tiny footprint", 4, "No subdomains / CT-log footprint", "crt.sh: none");

  // Placeholder image services
  if (/via\.placeholder\.com|placehold\.co|dummyimage\.com/i.test(html)) push("Placeholder image service", 9, "Ships placeholder image URLs", "via.placeholder.com");

  // AI assistant fingerprints
  const aiTools = html.match(/(\.cursorrules|\.cursor\/|copilot|chatgpt|claude\.ai|generated by|generated with|<!--generated)/gi) || [];
  if (aiTools.length) push("AI-generation fingerprints", 8, "Source mentions AI tools / 'generated with' comments", aiTools.slice(0, 3).join(", "));

  // Boilerplate forms
  const deadForm = html.match(DEAD_FORM_RE);
  if (deadForm) push("Template signup form", 6, "Stock newsletter/subscribe form with empty action", deadForm[0].slice(0, 90));

  // Low content depth
  const avgLen = pages ? 0 : 0;
  if (pages <= 2) push("Thin content", 6, `Only ${pages} page(s) — a prototype, not a product`, `${pages} pages crawled`);

  // Default favicon / assets
  if (/favicon\.ico/i.test(html) && !/\.svg/.test(html.match(/rel=["']?icon/g) ? "" : "")) push("Stock favicon", 4, "No custom favicon — browsers fall back to /favicon.ico", "/favicon.ico");

  let score = 100;
  const maxPossible = signals.reduce((a, s) => a + s.weight, 0);
  const actual = signals.reduce((a, s) => a + s.weight, 0);
  // Score = how much of the "full vibe" is present, normalized, plus a small baseline.
  score = Math.round(100 * Math.tanh(actual / 55));

  let label = "Custom build";
  if (score >= 70) label = "Full AI prototype";
  else if (score >= 45) label = "Template-ish build";
  else if (score >= 20) label = "Semi-custom build";

  return {
    score,
    label,
    signalCount: signals.length,
    signals: signals.slice(0, 20),
    summary: signals.length
      ? `Detected ${signals.length} vibe-coding signals (${maxPossible} possible). Highest-signal: ${signals[0]?.name}.`
      : "No obvious vibe-coding signals detected.",
  };
}
